# Generated by Django 3.2.4 on 2021-06-19 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='created',
            field=models.DateField(default=datetime.date(2021, 6, 19)),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(max_length=150, verbose_name='Answer'),
        ),
    ]
