# Generated by Django 3.2.4 on 2021-06-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
