# Generated by Django 3.2.4 on 2021-06-20 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='created',
            field=models.DateField(default=datetime.date(2021, 6, 20)),
        ),
    ]
